service: animalService

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET api/v1/animals

custom:
  bool:
    true: true
    false: false
  domainName: ${opt:domain, 'invalid.com'}
  deployDomain: ${opt:deployDomain, 'false'}
  customDomain:
    domainName: ${self:custom.domainName}
    basePath: animals # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.bool.${self:custom.deployDomain}}

plugins:
  - serverless-domain-manager
  - serverless-offline