service: animalService

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  list:
    handler: handler.list
    events:
      - http: GET api/v1/list

custom:
  bool:
    true: true
    false: false
  customDomain:
    domainName: ${opt:domain, 'invalid.com'}
    basePath: animals # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.bool.${opt:enableDomainManager, 'false'}}

plugins:
  - serverless-domain-manager
  - serverless-offline